
## Data Anaysis
-it is the process of collecting , cleaning , transforming and interpreting raw data to discover the useful insights and support decision making 

collecting , examining, cleaning, tranforming, organizing, & interpreting data to extract useful info


## 1.Pandas(panel-data)
it is a open source library used for data manipulation and data analysis

dat str :
- series(1D)
-  Dataframes(2D)
  
```python
import pandas as pd 
```

## Series
it is a One dimension array data structure that can hold any type of data, where each item has a specific index name

In [1]:
import pandas as pd
marks = [87,89,90,78]
series = pd.Series(marks)# as list
print(series)
line = '=========================================='
print(line)


index = pd.Series(marks, index =['a', 'b', 'c','d'])
print(index)
print(line)

# we use the loc for the locate the data 
print(series.loc[1])
print(index.loc['b'])
series.loc[1] = 200
print(series.loc[1])## it change the located value in the series not the marks data
print(index.loc['b'])
print(line)

print(index.iloc[1])# now in the index at position b the 89 present but we can also acces it though the index
print(line)

#we can apply condition in the series
print(series[series>=90])

0    87
1    89
2    90
3    78
dtype: int64
==========================================
a    87
b    89
c    90
d    78
dtype: int64
==========================================
89
89
200
89
==========================================
89
==========================================
1    200
2     90
dtype: int64

In [2]:
#series using dictionary
students = pd.Series({
    'rahul' : 21,
    'neha' : 24,
    "abhi" : 22,
    'rajunh' : 28,
    'anu' : 29,
    'shreya' : 35
})

print(students)
print(line)

students.loc["anu"]-=5
print(students.loc["anu"])
print(students[students<25])
print(line)

print(students)

rahul     21
neha      24
abhi      22
rajunh    28
anu       29
shreya    35
dtype: int64
==========================================
24
rahul    21
neha     24
abhi     22
anu      24
dtype: int64
==========================================
rahul     21
neha      24
abhi      22
rajunh    28
anu       24
shreya    35
dtype: int64

## Data Frames
A two-dimensional labeled , a tabular data structure with rows and columns.

In [3]:
data = {
    'name' : ["riya", "rahul", "arjunh"],
    'age' : [21,23,21],
    'marks' : [98,87,76]
}
df = pd.DataFrame(data)
print(df)
print(line)

#lets change the indec
df = pd.DataFrame(data, index=['a', 'b', 'c'])
print(df)
print(line)

# df.loc['row_label', 'column_label']
#df.loc[:, 'column_label']          # Single column
#df.loc[:, ['Col_A', 'Col_B']]      # Multiple columns

#lets access using loc 
print(df.loc['a']) # accesing the row
print(line)
print(df.loc[:,'marks']) # accesing the column}
print(line)

# add a column
df['hobby'] = ['swimming', 'reading', 'archery']
print(df)
print(line)

# add a new row
new_row = pd.DataFrame([
    {'name':'manu', 'age':19,'hobby':'vedic_scriptures'},
    {'name':'trupti', 'age':21,'marks':89,'hobby':'traveling'}],index =['d','e'])
df = pd.concat([df, new_row])
print(df)

     name  age  marks
0    riya   21     98
1   rahul   23     87
2  arjunh   21     76
==========================================
     name  age  marks
a    riya   21     98
b   rahul   23     87
c  arjunh   21     76
==========================================
name     riya
age        21
marks      98
Name: a, dtype: object
==========================================
a    98
b    87
c    76
Name: marks, dtype: int64
==========================================
     name  age  marks     hobby
a    riya   21     98  swimming
b   rahul   23     87   reading
c  arjunh   21     76   archery
==========================================
     name  age  marks             hobby
a    riya   21   98.0          swimming
b   rahul   23   87.0           reading
c  arjunh   21   76.0           archery
d    manu   19    NaN  vedic_scriptures
e  trupti   21   89.0         traveling

In [4]:
# null value
df.isnull()# - missing value
df.dropna()# - rows containg misssing values-- manu will get disappear

     name  age  marks      hobby
a    riya   21   98.0   swimming
b   rahul   23   87.0    reading
c  arjunh   21   76.0    archery
e  trupti   21   89.0  traveling

In [5]:
orders = {
    "Order_ID": [
        "ORD101",
        "ORD102",
        "ORD103",
        "ORD104",
        "ORD105",
        "ORD106",
        "ORD107",
        "ORD108",
    ],
    "Product": [
        "Laptop",
        "Headphones",
        "Mouse",
        "Laptop",
        "Keyboard",
        "Headphones",
        "Monitor",
        "Mouse",
    ],
    "Category": [
        "Electronics",
        "Accessories",
        "Accessories",
        "Electronics",
        "Accessories",
        "Accessories",
        "Electronics",
        "Accessories",
    ],
    "City": [
        "Pune",
        "Mumbai",
        "Pune",
        "Delhi",
        "Mumbai",
        "Pune",
        "Delhi",
        "Mumbai",
    ],
    "Quantity": [1, 2, 3, 1, 2, 1, 2, 4],
    "Price": [55000, 2000, 800, 55000, 1500, 2000, 12000, 800],
}

df = pd.DataFrame(orders)
print(df)
print(line)
selected = df[['Product','Category']]
print(selected)
print(line)

##show where quantity are greater than 2
print(df[df["Quantity"]>2])
print(line)

## oder from pune quantities are greater than 1
print(df[(df['Quantity']>1) & (df['City']=='Pune')])
print(line)

##calculate the revenue
df['revenue'] = df['Quantity']*df['Price']
print(df)
print(line)

##hight value
df['order_type'] = df['revenue'].apply(lambda x : 'High Value' if x>20000 else 'Normal')
print(df)
print(line)

##print only high value columns
print(df.loc[df['order_type']=='High Value'])
print(line)

# group by the city
group = df.groupby('City')['revenue'].sum()
print(group)
print('line')
print(df.groupby('City')['revenue'].mean())

  Order_ID     Product     Category    City  Quantity  Price
0   ORD101      Laptop  Electronics    Pune         1  55000
1   ORD102  Headphones  Accessories  Mumbai         2   2000
2   ORD103       Mouse  Accessories    Pune         3    800
3   ORD104      Laptop  Electronics   Delhi         1  55000
4   ORD105    Keyboard  Accessories  Mumbai         2   1500
5   ORD106  Headphones  Accessories    Pune         1   2000
6   ORD107     Monitor  Electronics   Delhi         2  12000
7   ORD108       Mouse  Accessories  Mumbai         4    800
==========================================
      Product     Category
0      Laptop  Electronics
1  Headphones  Accessories
2       Mouse  Accessories
3      Laptop  Electronics
4    Keyboard  Accessories
5  Headphones  Accessories
6     Monitor  Electronics
7       Mouse  Accessories
==========================================
  Order_ID Product     Category    City  Quantity  Price
2   ORD103   Mouse  Accessories    Pune         3    800
7   ORD108   Mouse  Accessories  Mumbai         4    800
==========================================
  Order_ID Product     Category  City  Quantity  Price
2   ORD103   Mouse  Accessories  Pune         3    800
==========================================
  Order_ID     Product     Category    City  Quantity  Price  revenue
0   ORD101      Laptop  Electronics    Pune         1  55000    55000
1   ORD102  Headphones  Accessories  Mumbai         2   2000     4000
2   ORD103       Mouse  Accessories    Pune         3    800     2400
3   ORD104      Laptop  Electronics   Delhi         1  55000    55000
4   ORD105    Keyboard  Accessories  Mumbai         2   1500     3000
5   ORD106  Headphones  Accessories    Pune         1   2000     2000
6   ORD107     Monitor  Electronics   Delhi         2  12000    24000
7   ORD108       Mouse  Accessories  Mumbai         4    800     3200
==========================================
  Order_ID     Product     Category    City  Quantity  Price  revenue  \
0   ORD101      Laptop  Electronics    Pune         1  55000    55000
1   ORD102  Headphones  Accessories  Mumbai         2   2000     4000
2   ORD103       Mouse  Accessories    Pune         3    800     2400
3   ORD104      Laptop  Electronics   Delhi         1  55000    55000
4   ORD105    Keyboard  Accessories  Mumbai         2   1500     3000
5   ORD106  Headphones  Accessories    Pune         1   2000     2000
6   ORD107     Monitor  Electronics   Delhi         2  12000    24000
7   ORD108       Mouse  Accessories  Mumbai         4    800     3200

   order_type
0  High Value
1      Normal
2      Normal
3  High Value
4      Normal
5      Normal
6  High Value
7      Normal
==========================================
  Order_ID  Product     Category   City  Quantity  Price  revenue  order_type
0   ORD101   Laptop  Electronics   Pune         1  55000    55000  High Value
3   ORD104   Laptop  Electronics  Delhi         1  55000    55000  High Value
6   ORD107  Monitor  Electronics  Delhi         2  12000    24000  High Value
==========================================
City
Delhi     79000
Mumbai    10200
Pune      59400
Name: revenue, dtype: int64
line
City
Delhi     39500.0
Mumbai     3400.0
Pune      19800.0
Name: revenue, dtype: float64

In [6]:
import pandas as pd

placement = {
    "Student": [
        "Aarav", "Isha", "Rohan", "Meera",
        "Kabir", "Ananya", "Vivek", "Sneha"
    ],
    "Department": [
        "Computer", "IT", "Computer", "Mechanical",
        "IT", "Computer", "Mechanical", "IT"
    ],
    "Company": [
        "TCS", "Infosys", "Wipro", "TCS",
        "Infosys", "Accenture", "Wipro", "TCS"
    ],
    "Package": [
        4.5, 3.8, 7.2, 6.0, 4.5, 5.2, 4.0, 3.8
    ],
    "Placement Status": [
        "Placed", "Placed", "Placed", "Placed",
        "Placed", "Placed", "Not Placed", "Placed"
    ]
}

df = pd.DataFrame(placement)
print(df)
print(line)

###avg package by department
print(df.groupby('Department')['Package'].mean())
print(line)

##count of student place in perticular company
print(df[df['Placement Status']=='Placed'].groupby('Company')["Student"].count())
print(line)

  Student  Department    Company  Package Placement Status
0   Aarav    Computer        TCS      4.5           Placed
1    Isha          IT    Infosys      3.8           Placed
2   Rohan    Computer      Wipro      7.2           Placed
3   Meera  Mechanical        TCS      6.0           Placed
4   Kabir          IT    Infosys      4.5           Placed
5  Ananya    Computer  Accenture      5.2           Placed
6   Vivek  Mechanical      Wipro      4.0       Not Placed
7   Sneha          IT        TCS      3.8           Placed
==========================================
Department
Computer      5.633333
IT            4.033333
Mechanical    5.000000
Name: Package, dtype: float64
==========================================
Company
Accenture    1
Infosys      2
TCS          3
Wipro        1
Name: Student, dtype: int64
==========================================

In [15]:
import pandas as pd

df = pd.DataFrame({
    "date": [
        "2026-08-01",
        "2026-08-02",
        "2026-08-03",
        "2026-08-04",
        "2026-08-05"
    ],
    "traffic": [120, 150, 180, 210, 190]
})

# Convert string to datetime
df["date"] = pd.to_datetime(df["date"])

# Extractingg date components
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["day_of_week"] = df["date"].dt.dayofweek
df["day_name"] = df["date"].dt.day_name()

print(df)

        date  traffic  year  month  day  day_of_week   day_name
0 2026-08-01      120  2026      8    1            5   Saturday
1 2026-08-02      150  2026      8    2            6     Sunday
2 2026-08-03      180  2026      8    3            0     Monday
3 2026-08-04      210  2026      8    4            1    Tuesday
4 2026-08-05      190  2026      8    5            2  Wednesday

In [16]:
print(
    df[
        (df['date']>"2026-08-01") 
        &
        (df['date']<"2026-08-04")
        
        ]
)

df[df["date"].between("2026-08-02", "2026-08-04")]

        date  traffic  year  month  day  day_of_week day_name
1 2026-08-02      150  2026      8    2            6   Sunday
2 2026-08-03      180  2026      8    3            0   Monday

        date  traffic  year  month  day  day_of_week day_name
1 2026-08-02      150  2026      8    2            6   Sunday
2 2026-08-03      180  2026      8    3            0   Monday
3 2026-08-04      210  2026      8    4            1  Tuesday